[tools]
go = "1.22"

[tasks."test-lazychezmoi"]
run = "go test ./..."
description = "Run lazychezmoi tests"

[tasks."build-lazychezmoi"]
run = "go build ./cmd/lazychezmoi"
description = "Build lazychezmoi binary"

[tasks."release-lazychezmoi-snapshot"]
run = "goreleaser release --snapshot --clean"
description = "Build lazychezmoi snapshot release"
