name: test

on:
  push:
    branches:
      - main
    paths:
      - "tools/lazychezmoi/**"
      - ".github/workflows/lazychezmoi.yaml"
  pull_request:
    branches:
      - main
    paths:
      - "tools/lazychezmoi/**"
      - ".github/workflows/lazychezmoi.yaml"

permissions:
  contents: read

jobs:
  build-test-vet:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: tools/lazychezmoi
    steps:
      - uses: actions/checkout@34e114876b0b11c390a56381ad16ebd13914f8d5 # v4.3.1
        with:
          persist-credentials: false
      - uses: actions/setup-go@40f1582b2485089dde7abd97c1529aa768e1baff # v5.6.0
        with:
          go-version-file: tools/lazychezmoi/go.mod
          cache-dependency-path: tools/lazychezmoi/go.sum
      - name: Build
        run: go build ./...
      - name: Test
        run: go test ./...
      - name: Vet
        run: go vet ./...
